name: Build

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "assets/**"
      - "package.json"
      - "package-lock.json"
      - "rollup.config.mjs"
      - "scripts/clean-dist.mjs"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Setup git
        run: |-
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git config --local user.name github-actions[bot]
          git config --global core.autocrlf true
          git config --global core.safecrlf false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Git commit
        id: commit
        run: |-
          git add --all
          git commit -m "CI build"
        continue-on-error: true

      - name: Git push
        uses: ad-m/github-push-action@master
        if: ${{ steps.commit.outcome == 'success' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Log
        if: ${{ steps.commit.outcome != 'success' }}
        run: echo Nothing to commit.
